version: '3.8'

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel
    db:
        image: postgres:16
        build:
            context: .
            dockerfile: Dockerfile.pgvector 
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-laravel}
            POSTGRES_USER: ${DB_USERNAME:-username}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-userpass}
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel        
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - "5050:80"
        depends_on:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: ${MAIL_FROM_ADDRESS}
            PGADMIN_DEFAULT_PASSWORD: ${MAIL_PASSWORD}
        networks:
            - laravel
    ollama:
        image: ollama/ollama
        container_name: ollama
        ports:
            - "11434:11434"
        networks:
            - laravel

    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
